### ISSUE TITLE
Error upgarde Moodle 4.3 to 4.4

### ISSUE THREAD

**Issue by nuria2c** [academic-moodle-cooperation/moodle-mod_offlinequiz#264] opened 2024-06-07 08:29 UTC
We know that the plugin version for moodle 4.4 is not available yet but in our TEST environment we've tried your plugin in Moodle 4.4 version because we had planned upgrade this summer (before september 2024). We use your plugin and we need to be sure that works, We will wait for your new version for the production upadte.

With moodle 4.4 you can create an Offline Quiz activity but you can't add questions. The error is

Exception - Failed opening required '[dirroot]/question/category_class.php' (include_path='[dirroot]/lib/pear:.:/opt/remi/php81/root/usr/share/pear:/opt/remi/php81/root/usr/share/php:/usr/share/pear:/usr/share/php')

This error is general in all moodle 4.4 upgrade because a the "/question/category_class.php"  file is no present in moodle 4.4

In this forum there is some information related
https://moodle.org/mod/forum/discuss.php?d=458073

**Comment by univietw** [comment] 2024-06-10 07:24
Thank you for your issue. This is a duplicate of #260 and already fixed in the master branch.

**Closed by univietw** 2024-06-10 07:24 UTC
Labels: duplicate
