### ISSUE TITLE
Cannot add questions under Boost theme (Offline Quiz 3.2.2 and Moodle 3.3)

### ISSUE THREAD

**Issue by frankkoch** [academic-moodle-cooperation/moodle-mod_offlinequiz#40] opened 2017-07-18 15:12 UTC
Hello

After creating a new Offline Quiz I cannot add questions to the quiz under Boost theme. The questions bank doesn't open and the error "You must select a question type" pops up when I try to create a new questions. However, both functionalities become available again when switching to More theme.

I tested Offline Quiz 3.2.2 on Moodle 3.3 with Chrome and Edge. Since 3.2.2 was tested under Boost, I'm surprised about this observation. Do you have any idea?

Kind regards, Frank

**Comment by univietw** [comment] 2017-07-19 06:18
Hello,

actually the offlinequiz 3.2 was not tested under boost. We only made a quick observation if everything is fine. Boost-functionality comes with 3.3, which we are still working on, since there were many issues this time. It will probably be released in the upcoming weeks.
Hope that helps
Thomas

**Comment by kaspot** [comment] 2017-07-19 11:34
We will also try to include the fix into 3.2 - added it to our bug tracking system.

**Comment by mkemmerling** [comment] 2017-08-14 04:32
Fixed in version 3.2.5, version for Moodle 3.3 not yet published.

**Comment by univietw** [comment] 2017-08-28 12:06
May I close this issue?

**Comment by webers-technikum-wien** [comment] 2017-08-29 07:33
do you know if version 3.2.5 will be compatible with moodle 3.1, and when it will be published?

**Comment by univietw** [comment] 2017-08-29 08:37
as version 3.2.5 is only for moodle 3.2, there won't be a 3.1-compatible version. You can use 3.1.3 instead or upgrade to moodle 3.2 if you want a specific feature.

This bugfix is only necessary for moodle 3.2, because boost was a new feature in version 3.2 The problem is fixed in Version 3.3 as well, which is already published.

**Comment by webers-technikum-wien** [comment] 2017-08-29 09:23
err sorry, my bad, we are using 3.3.1 not 3.1 so everything is fine :)

**Closed** 2017-09-12 11:42 UTC
