### ISSUE TITLE
German words in English language string

### ISSUE THREAD

**Issue by germanvaleroelizondo** [academic-moodle-cooperation/moodle-mod_offlinequiz#21] opened 2016-09-21 18:49 UTC
Hi,
When I was translating your offline quiz plugin in AMOS I noticed many German language words (eg, für) mixed with the English language words.

Can you please check questionsheetlatextemplate | offlinequiz  and replace the german language words with English words, so that the many Moodle translators at AMOS can easily translate this great plugin into many languages?

Thanks in advance for your help.

**Comment by kaspot** [comment] 2016-09-22 06:39
Thanks for reporting this - I already forwarded it to our developer.

**Comment by univietw** [comment] 2016-10-21 10:13
the problem is fixed in the master branch, which is the develop branch for 3.2

**Closed by univietw** 2016-10-21 10:13 UTC
