### ISSUE TITLE
idnumber on student list is not complete

### ISSUE THREAD

**Issue by ghost** [academic-moodle-cooperation/moodle-mod_offlinequiz#142] opened 2021-02-16 14:05 UTC
[2021 - 02-13 - Offline Quiz - Problema codice ID.pdf](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/files/5989046/2021.-.02-13.-.Offline.Quiz.-.Problema.codice.ID.pdf)
Hi,
I really don't know if this is an issue or a problem of my part. I'm sorry for that.
I performed some test of the plugin and now configuration is OK and it run very well, but I still have a little problem with the student list. I can't see the student idnumber complete, the frist digit is not visible.
Could you please inform me about this "issue".
Thank you very much.

**Comment by univietw** [comment] 2021-06-22 14:52
hello david,
sorry for answering so late. Have you selected the right amount of digits in the useridentification field? It should look like this:
[7]=idnumber

**Comment by DavidDelco** [comment] 2021-07-01 20:20
Hi,
Thank for your answer, late is better as never! 👍:-)
Yes I've selected 7 digit.
See attached file.

Thank you.
DD

[7-digit.pdf](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/files/6750563/7-digit.pdf)

**Comment by goggo24** [comment] 2023-12-01 11:34
As we couldn't reproduce the bug and no more information has been shared, we are closing this issue. For us useridenticifation with [9]=idnumber works fine.

**Closed by goggo24** 2023-12-01 11:34 UTC
Labels: bug
