### ISSUE TITLE
Shuffle not working

### ISSUE THREAD

**Issue by monicangela** [academic-moodle-cooperation/moodle-mod_offlinequiz#209] opened 2023-10-13 09:42 UTC
Hello,

With version v4.1.0 (2023070701) on a Moodle 4.1 the question shuffle is not working. The groups have the same order even if we click on the "Shuffle answers/Reload question list"

Is it possible to fix this ?
Thanks,
Monica

**Comment by LisaE14** [comment] 2023-10-16 05:32
Hello, we can confirm this problem on Moodle 4.1.5+ and offline quiz 2023070701.

**Comment by Syl20D20** [comment] 2023-10-23 13:10
Hello,
I have the same problem on Moodle 4.1.6+ and offline quiz 2023070701.

**Comment by goggo24** [comment] 2023-10-24 07:59
Thanks for reporting - we are just preparing v.4.2.0 where shuffle already works again and backport it afterwards. Please be patient. Thanks.

**Comment by moodleulpgc** [comment] 2023-11-09 12:43
Hi, we at ULPGC saw this a couple of weeks ago too.  The failure to generate random exams when using several Groups/templates is quite a showstopper for may of our teachers.  Do you have a time expectation to fix this bug?? 

Or a tip to try to correct it myself. 
I see in locallib.php the functions   
   offlinequiz_get_group_template_usage() and 
   offlinequiz_shuffle_questions()  

But probably the problem is in createquiz.php itself.   Obviously the concern is randomize questions not only for output (doable  with explicit shuffle of $templateusage array  in createquiz.php) but keeping that order usage for the scan/correction phase.   

I have a lot of teachers waiting for this being corrected; I can invest some time in fixing it, , with some help, in our site and put it back in github.

**Comment by univietw** [comment] 2023-11-16 13:02
we are still working on 4.2.0 which will be released pretty soon.
Until then you can delete the following line:
    srand((int)microtime() * 1000000); // For php < 4.2.
in the locallib. This will fix the issue.
I am already working on all the backports for 4.1

**Comment by ndunand** [comment] 2023-11-16 13:21
I can confirm that removing the `srand()` function call seems to fix the issue. Question and answer propositions now shuffle as needed.

Using `mod_offlinequiz` 20232023070701 on Moodle 4.2.3 2023042403

**Comment by moodleulpgc** [comment] 2023-11-18 09:35
Hi, yes, confirmed, commenting out  srand() in locallib.php returns shuffling. 
Using mod_offlinequiz  2023070701 with moodle 4.1.6+ (Build: 20231102

**Comment by Syl20D20** [comment] 2023-11-20 07:36
Hello,
I also confirm that it works on Moodle 4.1.6+ and offline quiz 2023070701.

Thanks !

**Comment by crnfpp** [comment] 2023-11-22 11:16
hi!
is the dev version available somewhere to test the fix? 
I'm not finding it here on github and the main one seems not synced with the version i see on moodle plugin official website
https://moodle.org/plugins/mod_offlinequiz/versions

Thanks!

**Comment by univietw** [comment] 2023-11-23 14:24
@crnfpp I just pushed the backport402to401 branch to test it. We will probably publish it very soon.

**Comment by goggo24** [comment] 2023-11-30 16:16
Thanks for your feedback and testing - we have just released v.4.1.2/v.4.2.0. Please note https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/issues/220 before you update! The fix for the deprecation notice will be included in our next minor version.

**Closed by goggo24** 2023-11-30 16:16 UTC
Labels: bug
