### ISSUE TITLE
Upload .pdf is not allowed "imagenotsupported'

### ISSUE THREAD

**Issue by Nirnae** [academic-moodle-cooperation/moodle-mod_offlinequiz#218] opened 2023-11-27 08:46 UTC
Hi, I've been trying to use offlinequiz correction, it's working perfectly with .jpeg,.tiff and such, but when I try to upload a .pdf I get the following answer :

"Image not supported" - "test.pdf has image type"

and here is the value of $scannedpage :
```

C:\wamp64\www\moodle\moodle-MOODLE_39_STABLE\mod\offlinequiz\correct.php:117:
object(stdClass)[119]
  public 'id' => string '4' (length=1)
  public 'offlinequizid' => string '2' (length=1)
  public 'resultid' => null
  public 'filename' => null
  public 'warningfilename' => null
  public 'groupnumber' => null
  public 'userkey' => null
  public 'pagenumber' => null
  public 'time' => string '1700751796' (length=10)
  public 'status' => string 'error' (length=5)
  public 'error' => string 'imagenotsupported' (length=17)
  public 'info' => string 'test.pdf has image type ' (length=42)
  
```
  
  I'm using offlinequiz release   = "v3.9.1";

Did anyone already met that kind of issue or/and found a fix ?

**Comment by goggo24** [comment] 2023-11-30 19:04
It should be scanned in black and white with 200 - 300 dpi and, if possible on your device, with the "text" setting. Depending on the scanner, different settings may lead to better recognition rates. If necessary, test out different settings on your device.

**Comment by mwreichel** [comment] 2023-12-06 11:02
This is a duplicate of the issue #199.

**Closed** 2024-05-16 07:17 UTC
Labels: duplicate, provide feedback
