### ISSUE TITLE
develop_402 branch early feedback

### ISSUE THREAD

**Issue by ndunand** [academic-moodle-cooperation/moodle-mod_offlinequiz#216] opened 2023-11-17 09:48 UTC
(continuing discussion from #205  in a proper dedicated thread)

Thanks @univietw ,

So on `develop_402` I've noticed the following:

1. If you create an offlinequiz with 2 groups (A and B) and put question1 in both groups, then modify question1 (so it's now on v2). If you change the question1 version in group B (for example back to v1) this is impossible ; If you change the question1 version (e.g. back to v1) in group A it works, but (even though the change to v1 appears to be done only in group A and not in group B according to the offline quiz questions layout UI) the questin1 version is actually changed in _both_ groups A and B. I guess this makes sense but the interface is confusing, as it shows q1v1 in group A and q1v2 in group B but in the PDF it is q1v1 in both.

(I hope this is clear enough to be understandable)

2. When grading or re-grading, the following does not work exactly as expected (I can test again if necessary)
 - if I want to get rid of a question that didn't work (for instance if I notice after the exam that the question was wrongly stated), I used to change the weight of that question to 0 (zero) and re-grade. However in some cases now this leads to the total grade to be recomputed correctly but not the grade itself, as the question is still counted. For example a student that had all correct had 10/10 points, after removing the question (using weight=0 as described above) he has now 10/9 points.

**Comment by ndunand** [comment] 2023-11-17 10:00
bump @acamacho-unige , @CamilleTrd , @abowman-unige , @Benjamin-unige

**Comment by univietw** [comment] 2023-11-17 10:30
regarding 1.) This is intended. The version in all groups should be the same on all groups. Maybe we should make this more clear to the user.
regarding 2.) That's an interesting bug. In my tests this has already worked, but it might come through one of the maybe 50 patches we have done in the last months. I will retest it.

**Comment by univietw** [comment] 2023-11-17 11:18
Can you tell me how to reproduce 2)? It works for me just as intended.

**Comment by ndunand** [comment] 2023-11-17 14:36
1) Understood ; thanks

2) I must have tested badly yesterday night ; I tested again from scratch today and it seems to work correctly in both cases when I change the correct answer or the question weight

sorry for misreporting about this 2nd point

**Comment by ndunand** [comment] 2023-11-17 15:24
Also a deprecation notice display in Preparation > Questions : 

> The question/qengine.js has been deprecated. Please use core_question/question_engine
line 448 of /lib/outputrequirementslib.php: call to debugging()
line 381 of /mod/offlinequiz/edit.php: call to page_requirements_manager->js()

**Comment by goggo24** [comment] 2023-11-30 16:18
Thanks for your feedback and testing - we have just released v.4.2.0 and v. 4.1.2. Please note https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/issues/220 before you update! The fix for the deprecation notice will be included in our next minor version.

**Closed by goggo24** 2023-11-30 16:18 UTC
