### ISSUE TITLE
import fails because of imagemagicks memory limit

### ISSUE THREAD

**Issue by webers-technikum-wien** [academic-moodle-cooperation/moodle-mod_offlinequiz#96] opened 2019-03-13 14:35 UTC
we are currently trying to get offline quizzes to run at our site, but running into multiple issues.

one of them I was able to track down and solve with a workaround. maybe it only exists with pdf or is specific to our printers/scanners, but i'm posting it here for reference:

- all our scanners scan to .pdf
- we tried different scan settings along with the recommended settings
- we always ended up with only 3 imported pages from the pdf (which had over 30 pages)
- when looking into /moodledata/temp/offlinequiz/import we could see that the first 3 pages of the pdf were converted into huge TIFFs (17 MB each), and the rest of the pages into tiny pseudo-TIFF files that only had 2KB each and were clearly broken
- when running imagemagick convert manually on the command line, it became apparent that it runs out of memory trying to convert the pdf into TIFFs (https://github.com/ImageMagick/ImageMagick/issues/396)
- after adjusting imagemagick memory limit in /etc/ImageMagic-6/policy.xml, the import worked

I recommend you either add imagemagick memory issues to your documentation, or maybe adjust the command lines for the converts in order to increase the memory limit (http://www.imagemagick.org/script/command-line-options.php#limit)

maybe even make it adjustable in moodle?

**Comment by univietw** [comment] 2019-05-08 07:21
Hi, Thank you for the bug report. I reproduced your bug at my local instance. I added the information in the README.md It will be in the next 3.6 Minor and 3.7 release.
I chose not to adjust the size since I can't give any recommendation yet, how big the memory needs to be. It also seems that PDF conversion has a huge memory consumption in comparison to e.g. TIFF. For my test it was ~5x the size of the uploaded PDF. With tiff I couldn't reproduce the bug even with a huge file. If this problem occurs more often I will look more deeply into it.

**Closed by univietw** 2019-05-08 07:21 UTC
Labels: bug
