### ISSUE TITLE
A required (item) parameter is missing!

### ISSUE THREAD

**Issue by emrahdirek** [academic-moodle-cooperation/moodle-mod_offlinequiz#54] opened 2017-12-22 13:13 UTC
Moodle 3.3.3+ I using. I get this error when I select the option to rotate the exam when I want to edit the wrong exam. Can you help me.
![screenhunter 48](https://user-images.githubusercontent.com/34771540/34299252-08b56394-e733-11e7-9e03-22100efe3f24.jpg)

**Comment by univietw** [comment] 2018-01-12 12:02
Have you tried reuploading your file? I never had this error and it was tested before release, and nor can I reproduce this bug on my local machine.

**Comment by goggo24** [comment] 2019-04-05 09:11
I will close the issue, because we didn't get more information from you and cannot reproduce it in our systems. In the meantime there are also "newer" versions of offline quiz available. 
Hope it works now for you. Bye, Eva.

**Closed by goggo24** 2019-04-05 09:11 UTC
